### ISSUE TITLE
License inconsistency?

### ISSUE THREAD

**Issue by pombredanne** [mischasan/aho-corasick#12]
@mischasan Your readme states the code if GPL-licensed. The license is an LGPL 3. Your code has LGPL headers with no version stated.... Can you clarify which is the correct license?
Thanks!

**Comment by mischasan** [comment]
Cool: wasn't aware of the distinction, and the text I copy-pasted was missing that digit :-)

**Comment by mischasan** [comment]
So that's updated. LGPL V3 has been around since 2007? 2008? didn't realize
the fine point of the license.
Out of curiosity, are you vetting github source, or is acism you were
interested in using?

**Comment by pombredanne** [comment]
@mischasan I am interested in acism and I may craft a python binding for it.

**Comment by pombredanne** [comment]
Thanks for your quick response!

**Comment by mischasan** [comment]
Cool. Let me know. I've tweaked some tiny stuff, but nothing that I
couldn't change and check in more than 30 minutes.
