### ISSUE TITLE
callback function text position value

### ISSUE THREAD

**Issue by alonbg** [mischasan/aho-corasick#14]
cb(int strnum, int textpos, <context>)
call back function passed to acism_more/scan is called with textpos value being the length of the input string. This length is known in advance, if desired, it can be passed as part of the context.
It would be much more useful if textpos value would be the suffix position matched (i.e. the length of the string represented by strnum).

Regards,
Alon

**Comment by mischasan** [comment]
Sorry, disagree on a few counts ...

The engine does not store string lengths, nor can it calculate them from the machine, without major effort.  As soon as it traverses a backlink, it has no idea of the depth of that node (and doesn't need to), You'll notice that the callback is given the *end* offset of the string in the match buffer. With acism_more(), the start of the string might not even be in the current input text buffer. 

To do what you ask for, acism_create() would have to store the prefix length in every node that's the target of a backlink ... but that reduces how much data  can compile, in the 32bit model. There are a lot of applications that only need to know the string number; so I didn't burden the engine with what can be handled using the string number ...

The caller provides the array of <length, data> pairs to acism_create(), so it knows the lengths. The caller can create a vector of lengths, and use the strnum as an O(1) lookup. That length vector can be (or be part of) the context object that's passed to the callback. That's what you need, right?

I don't understand strlen being *more* useful than textpos; they are two different independent pieces of information about the match.

HTH
Mischa

**Comment by alonbg** [comment]
Appreciate you took the time to answer and I stand corrected :)
Thank you for this piece of software. Performance of the related model is x20 faster.

I have ~10^6 suffixes. ~150 of them have additional handling.
I ended doing what you suggested - placing them first in the input to acism_create ( In a know in advance order. Postion 0 is reserved for an invalid input)
If ( strnum > 0 && strnum <= max ) v[strnum](...);
Fact is I had to replace strings hash lookup with simple integer lookup (strnum). It fast !!

Thanks,
Alon

**Comment by mischasan** [comment]
Cool. BTW I'm always interested in what people use acism for ...

**Comment by alonbg** [comment]
It holds domain suffixes.
had to build acism with all strings prefixed and suffixed like so .<domain>$
Also input strings are prefixed/suffixed before match.
Otherwise, for example, I may get the following matchs:
input xfoo.com is matched by foo.co
fook.afbar.co by k.af
www.tesfoo.com by foo
