### ISSUE TITLE
Uninitialized flags in acism struct

### ISSUE THREAD

**Issue by BabeleDunnit** [mischasan/aho-corasick#19]
Hi Mischa, 

me again :)

I just noticed that the flags in struct acism you use to check if any mmap() operation has been performed (load/save), and eventually call munmap() in acism_destroy(), is not initialized in acism_create(). So, you could call erroneously

https://github.com/mischasan/aho-corasick/blob/master/acism_file.c#L83

even if no mmap() operations have been performed, because of dirty memory (which is BTW what is happening to me right now :) :) )

Later,
Aaron

**Comment by mischasan** [comment]
acism_create(MEMREF const* strv, int nstrs)
{ ...
  ACISM *psp = *calloc*(1, sizeof*psp);
....

**Comment by BabeleDunnit** [comment]
Wooot. I see. This is STRANGE.

Let me double check.

> Il giorno 07 ott 2016, alle ore 21:35, Mischa Sandberg <notifications@github.com> ha scritto:
> 
> acism_create(MEMREF const* strv, int nstrs)
> { ...
> ACISM *psp = *calloc*(1, sizeof*psp);
> ....
>

**Comment by BabeleDunnit** [comment]
Rookie error. I was missing a brace :)
thx
