### ISSUE TITLE
add_backlinks possible bug

### ISSUE THREAD

**Issue by zxxunkxzhx** [mischasan/aho-corasick#38]
at following statement:
dstp->is_suffix = bp->match || bp->is_suffix;

if bp->match is not zero, there maybe an effect of
dstp->is_suffix = (char)bp->match;
transforming from the **match** type into **char** type involve data loss

**Comment by mischasan** [comment]
Not a bug.
'||' is a boolean operator, not a bitwise-or

match is at least uint32. is_suffix is a char.
Compile this and test it with (suffix) 0 1 2 256 and (match) 0 1 2 256
4294967296
The output will always be 0 or 1.

$ cat try.c
#include <stdio.h>
int main(int argc, char** argv)
{
        char    suffix;
        int        match;
        sscanf(argv[1], "%d", &match);
        suffix = match;
        sscanf(argv[2], "%d", &match);
        suffix = suffix || match;
        printf("%d\n", suffix);
}

hth
On 10/03/2021, zxxunkxzhx ***@***.***> wrote:
> at following statement:
> dstp->is_suffix = bp->match || bp->is_suffix;
>
> if bp->match is not zero, there maybe an effect of
> dstp->is_suffix = (char)bp->match;
> transforming from the **match** type into **char** type involve data loss

-- 
Engineers think equations approximate reality.
Physicists think reality approximates the equations.
Mathematicians never make the connection.

**Comment by zxxunkxzhx** [comment]
got it , thanks
